# Generated by Django 5.0.1 on 2024-02-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_merge_20240207_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name_kana',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name_kana',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
